<?php

namespace Tests\Unit;

use App\Country;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class CountryTest extends TestCase
{
    use DatabaseTransactions;

    protected $header = [];
    protected $country;


    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->header['Accept'] = 'application/json';
        $this->country = factory(Country::class)->create();
    }

    /**
     * A basic test for creating a country.
     *
     * @return void
     */
    public function testCreateCountry()
    {
        $response = $this->withHeaders([
            'Content-Type' =>  $this->header['Accept']
        ])->json('POST', 'api/v1/country', ['name' => 'Nigeria']);

        $response->assertStatus(200)->assertJsonFragment([
            'status' => 'success',
            'data' => null
        ]);
    }

    public function testInvalidCountry()
    {
        $response = $this->withHeaders([
           'Content-Type' =>  $this->header['Accept']
        ])->json('POST', 'api/v1/country', ['name' => '']);

        $response->assertStatus(200)->assertJsonFragment([
            'status' => 'error',
            'data' => null
        ]);
    }

    public function testCountryWithInteger()
    {
        $response = $this->withHeaders([
            'Content-Type' => $this->header['Accept']
        ])->json('POST', 'api/v1/country', ['name' => 123456788]);

        $response->assertStatus(200)->assertJsonFragment([
            'status' => 'error',
            'data' => null
        ]);
    }
}
