<?php

namespace Tests\Unit;

use App\Country;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class CountryTest extends TestCase
{
    use DatabaseTransactions;

    protected $header = [];
    protected $country;


    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->header['Accept'] = 'application/json';
        $this->country = factory(Country::class)->create();
    }

    /**
     * A basic test for creating a country.
     *
     * @return void
     */
    public function testCreateCountry()
    {
        $response = $this->withHeaders([
            'Content-Type' => $this->header['Accept']
        ])->json('POST', '/api/v1/country', ['name'=> $this->country->name ]);

        $response->assertStatus(200)->assertJsonFragment([
            'status' => 'success',
            'error' => null
        ]);
    }
}
